name: Workflow Conclusion
author: Sarisia

outputs:
  conclusion:
    description: Workflow conclusion. `success` or `failure`.
    value: ${{ fromJSON(steps.ghapi.outputs.result).conclusion }}
  jobs:
    description: Number of jobs in workflow. This includes the jobs currently running.
    value: ${{ fromJSON(steps.ghapi.outputs.result).jobs }}

runs:
  using: "composite"
  steps:
    - uses: actions/github-script@98814c53be79b1d30f795b907e553d8679345975
      id: ghapi
      with:
        script: |
          const jobs = await github.paginate(
            github.rest.actions.listJobsForWorkflowRun,
            {
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.runId
            }
          )

          const ret = {
            conclusion: jobs.filter(job => job.conclusion !== null && job.conclusion !== "success")
                          .length > 0 ? 'failure' : 'success',
            jobs: jobs.length
          }
          console.log(ret)

          return ret
