name: Build and push devcontainer image
author: Sarisia

inputs:
  imageName:
    description: Image name
    default: ghcr.io/${{ github.repository }}/devcontainer
  subFolder:
    description: Relative path contains .devcontainer directory (or devcontainer.json)
    default:

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

    - uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - uses: devcontainers/ci@96af31b963e2ff6b5be0f96195a92f0c844c52b4
      with:
        imageName: ${{ inputs.imageName }}
        subFolder: ${{ inputs.subFolder }}
        push: always
