# List actions used in composite action.yml here
# to let the Dependabot detect newer action versions.
# Do not run this workflow!

name: Dependabot dummy
on:
  workflow_dispatch:

jobs:
  list:
    if: false
    runs-on: ubuntu-latest
    steps:
      # conclusion
      - uses: actions/github-script@98814c53be79b1d30f795b907e553d8679345975

      # update-devcontainer
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      - uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      - uses: devcontainers/ci@96af31b963e2ff6b5be0f96195a92f0c844c52b4
