name: test conclusion (failure)
on:
  pull_request:
  push:
    paths:
      - 'conclusion/**'


jobs:
  matrix-task:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - run: echo runnning on ${{ matrix.os }}
        shell: bash
      - run: exit 1
        shell: bash
    
  conclusion:
    needs: matrix-task
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./conclusion
        id: conclusion
      - name: assert conclusion
        if: steps.conclusion.outputs.conclusion != 'failure'
        run: |
          echo "::error::Conclusion mismatch (expected: failure, got: ${{ steps.conclusion.outputs.conclusion }})"
          exit 1
