name: test conclusion (success)
on:
  pull_request:
  push:
    paths:
      - 'update-devcontainer/**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: ./update-devcontainer
        with:
          imageName: ghcr.io/${{ github.repository }}/test-update-devcontaienr
          subFolder: update-devcontainer
